export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const CLEAR_INGREDIENTS = "CLEAR_INGREDIENTS";
export const PURCHASED_STATUS = "PURCHASED_STATUS";
